# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('position', models.TextField(blank=True, default=None, null=True)),
                ('contacts', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
