# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('team_leader', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price', models.FileField(blank=True, default=None, null=True, upload_to='images/')),
                ('trademark', models.TextField(blank=True, default=None, null=True)),
                ('worker_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Worker')),
            ],
        ),
    ]
