# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tradingteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingteams',
            name='nam',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tradingteams',
            name='worker_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='main.Worker'),
        ),
        migrations.AlterField(
            model_name='tradingteams',
            name='worker_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='main.Worker'),
        ),
    ]
