# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180613_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingteams',
            name='worker_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_3', to='main.Worker'),
        ),
        migrations.AlterField(
            model_name='tradingteams',
            name='team_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='main.Worker'),
        ),
        migrations.AlterField(
            model_name='tradingteams',
            name='worker_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_1', to='main.Worker'),
        ),
        migrations.AlterField(
            model_name='tradingteams',
            name='worker_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_2', to='main.Worker'),
        ),
    ]
