# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180613_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structural_unit', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('name_vacancy', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='foto',
        ),
    ]
