# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180621_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingteams',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='tradingteams',
            name='worker_1',
        ),
        migrations.RemoveField(
            model_name='tradingteams',
            name='worker_2',
        ),
        migrations.RemoveField(
            model_name='tradingteams',
            name='worker_3',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
