# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180705_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='logotip',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
