# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_logotip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingteams',
            name='picture',
        ),
        migrations.AddField(
            model_name='logotip',
            name='image_11',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='logotip',
            name='image_12',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tradingteams',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
