# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180711_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingteams',
            name='brands_logo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Logotip'),
        ),
    ]
