# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
