# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180814_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(blank=True, default=None, null=True, verbose_name='текст повідомлення')),
            ],
        ),
    ]
