# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180820_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='comments_message',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Message'),
            preserve_default=False,
        ),
    ]
