# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 10:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180820_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancykiev',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
