# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 10:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180923_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyberezan',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancynivki',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyoblast',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyzhitomir',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
