# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180923_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
