# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180923_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='tradingteams',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='vacancyberezan',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансиї'},
        ),
        migrations.AlterModelOptions(
            name='vacancykiev',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансиї'},
        ),
        migrations.AlterModelOptions(
            name='vacancynivki',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансиї'},
        ),
        migrations.AlterModelOptions(
            name='vacancyoblast',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансиї'},
        ),
        migrations.AlterModelOptions(
            name='vacancyzhitomir',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансиї'},
        ),
    ]
