# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180923_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='tradingteams',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='vacancykiev',
            options={'verbose_name': 'Вакансии Выдубичи', 'verbose_name_plural': 'Вакансию'},
        ),
    ]
