# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180923_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancykiev',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии Выдубичи'},
        ),
    ]
