# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180923_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы на Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='vacancyberezan',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии Березань'},
        ),
        migrations.AlterModelOptions(
            name='vacancykiev',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии Выдубычи'},
        ),
        migrations.AlterModelOptions(
            name='vacancynivki',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии Нивки'},
        ),
        migrations.AlterModelOptions(
            name='vacancyoblast',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии Петровцы'},
        ),
        migrations.AlterModelOptions(
            name='vacancyzhitomir',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии Житомир'},
        ),
    ]
